server:
  port: 5556
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security
    username: kaka
    password: postgres

  devtools:
    livereload:
      #      port: 35731
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: true
    open-in-view: false
    database: postgresql

  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 318540687189-sto2qjfbdl5hmc1p5p74rkl8t2691ae4.apps.googleusercontent.com
#            client-secret: b-mHTBIRKZ0bhNJy-zvWoLJF
#            scope:
#              - email
#              - profile
#          facebook:
#            client-id: 699160594579342
#            client-secret: 3e58ef3c91a092a7b00976d5e333c374
#            scope:
#              - email
#              - public_profile
#
#          naver:
#            client-id: wMVc6bfzMWuL16ZDKGV_
#            client-secret: 7foII6DFpo
#            clientAuthenticationMethod: post
#            scope:
#              - name
#              - email
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:5555/login/oauth2/code/naver
#
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response #?????


